export default {
  "updating": "Updating",
  "jars": "Server Softwares",
  "optimization": "Server Optimization",
  "world-reset": "World Reset",
  "domain": "Using A Domain",
  "java-version": "Changing Java Version",
  "datapacks": "Datapacks",
  "spark": "Spark",
  "timings": "Taking a Timings Report",
  "icon": "Icon",
  "motd": "How to change MOTD",
  "whitelist": "Setting up Whitelist",
  "resourcepack": "Serverwide Resource packs",
  "converting-worlds": "Converting Bukkit Worlds to vanilla",
  "waterfall": "Setting up a Waterfall/Bungee Server",
  "velocity": "Setting up a Velocity Proxy",
  "binarysearch": "Troubleshooting: Binary Search",
  "worlds": "Managing Worlds",
  "mcaselector": "MCASelector CLI",
  "exploitfix": "❗ Exploit Fix ❗",
  "anti-xray": "Enable Anti-Xray",
  "basic-server-commands": "Basic Server Commands",
  "bedrock-addons": "Install Bedrock Add-ons",
  "change-world-seed": "Change Your World Seed",
  "check-ping": "How to check your Minecraft ping",
  "common-server-properties": "Common server.properties Settings",
  "enable-command-blocks": "Enable Command Blocks",
  "hybrid-servers": "Hybrid Servers (Mods and Plugins)",
  "join-from-any-version": "Let Players Join From Any Version",
  "limit-world-size": "Limit World Size",
  "mob-spawn-limits": "Change Mob Spawn Limits",
  "modpack-packet-errors": "Fix 'Failed to decode packet' in modpacks",
  "offline-mode": "Offline (cracked) mode and how to secure it",
  "online-mode": "Online Mode Explained",
  "op-yourself": "Make Yourself an Operator",
  "prevent-seed-cracking": "Prevent Seed Cracking",
  "reset-nether": "Reset the Nether or End",
  "reset-player-data": "Reset Player Data",
  "server-software-overview": "Server Software Overview",
  "share-logs": "Share Your Server Logs",
  "troubleshooting": "Troubleshooting"
}
