export default {
  "ajParkour": "ajParkour",
  "banannouncer": "Ban Announcer",
  "citizens2": "Citizens 2",
  "conditionalcommands": "Conditional Commands",
  "coreprotect": "CoreProtect",
  "craftingstore": "Craftingstore",
  "discordsrv": "DiscordSRV",
  "essentialsx": "EssentialsX",
  "floodgate": "Floodgate",
  "geysermc": "GeyserMC",
  "geyseraddons": "GeyserAddons",
  "griefprevention": "GriefPrevention",
  "multiverse": "Multiverse",
  "papi": "PlaceholderAPI",
  "prism": "Prism",
  "servernpc": "ServerNPC",
  "tebex": "Tebex (BuyCraft)",
  "topper": "Topper",
  "vault": "Vault",
  "venturechat": "VentureChat",
  "viaversion": "ViaVersion",
  "votifier": "NuVotifier",
  "vulcan": "Vulcan Anticheat",
  "worldguard": "WorldGuard",
  "oraxen": "Oraxen",
  "denizen": "Denizen",
  "ajLeaderboards": "ajLeaderboards",
  "AdvancedEnchantments": "AdvancedEnchantments",
  "CMI": "CMI"
}
